name: Release new Version

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK 21
        uses: actions/setup-java@v4.1.0
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Build with Maven
        run: mvn clean package
      - name: Extract version
        id: pom
        run: echo "::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)"
      - uses: elgohr/Github-Release-Action@v5
        with:
          title: "Release: v${{ steps.pom.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: List target directory
        run: ls -l ./target
      - name: Get latest release
        id: latest_release
        run: |
          RELEASE_ID=$(curl --silent --show-error --header "Authorization: Bearer ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq .id)
          echo "::set-output name=id::$RELEASE_ID"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Find asset
        id: find_asset
        run: |
          ASSET_PATH=$(find ./target -name "TimetableGenerator-${{ steps.pom.outputs.version }}.jar" -maxdepth 1)
          echo "::set-output name=path::$ASSET_PATH"
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.latest_release.outputs.id }}/assets
          asset_path: ${{ steps.find_asset.outputs.path }}
          asset_name: TimetableGenerator-${{ steps.pom.outputs.version }}.jar
          asset_content_type: application/java-archive