name: Release new Version

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK 21
        uses: actions/setup-java@v4.1.0
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Build with Maven
        run: mvn clean package
      - name: Extract version
        id: pom
        run: echo "::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)"
      - uses: CupOfTea696/gh-action-auto-release@v1.0.2
        with:
          title: "Release: v${{ steps.pom.outputs.version }}"
          tag: 'v${{ steps.pom.outputs.version }}'
          draft: false
          regex: "/.*/i"
          changelog: 'CHANGELOG.md'
          changelog-entry: '## [v${{ steps.pom.outputs.version }}] - ${{ github.event.head_commit.timestamp }}\n\n${{ github.event.head_commit.message }}\n\n'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/TimetableGenerator-${{ steps.pom.outputs.version }}.jar
          asset_name: TimetableGenerator-${{ steps.pom.outputs.version }}.jar
          asset_content_type: application/java-archive